[project]
name = "sara-llm-proxy"
version = "0.0.0"
description = "WebSocket proxy that streams completions from a local LLM"
requires-python = ">=3.12"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"