# compose/core.yml
version: "3.9"               # optional – Docker 25 ignores it

x-env: &common-env
  TZ: America/New_York
  PUID: 1000                 # ubuntu
  PGID: 1000

services:
  redis:
    image: redis:7.2-alpine
    command: ["redis-server", "--appendonly", "yes"]
    environment: *common-env
    volumes:
      - redis-data:/data
    networks: [ backend ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  nats:
    image: nats:2.10-alpine
    command: ["-js", "-m", "8222"]                 # JetStream + monitor UI
    environment: *common-env
    networks: [ backend ]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:16-alpine
    environment:
      <<: *common-env
      POSTGRES_USER: sara
      POSTGRES_PASSWORD: sara_pw
      POSTGRES_DB: sara
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks: [ backend ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sara"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Pre-built tiny image that runs scripts/health_check.py
  healthcheck:
    build:
      context: ..                                 # repo root (one up from compose/)
      dockerfile: services/healthcheck/Dockerfile
    environment: 
      - ENV=prod 
    depends_on:
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks: [ backend ]
    ports:
      - "8000:8000"

volumes:
  redis-data:
  pg-data:

networks:
  backend:
    driver: bridge

