version: "3.9"

x-common-env: &common-env
  TZ: America/New_York
  PUID: 1000          # ubuntu
  PGID: 1000

services:
  redis:
    image: redis:7.2-alpine
    command: ["redis-server", "--appendonly", "yes"]
    environment:
      <<: *common-env
    volumes:
      - redis-data:/data
    networks: [ backend ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  nats:
    image: nats:2.10-alpine
    command: ["-js", "-m", "8222"]           # JetStream + monitoring
    environment: *common-env
    networks: [ backend ]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:16-alpine
    environment:
      <<: *common-env
      POSTGRES_USER: sara
      POSTGRES_PASSWORD: sara_pw
      POSTGRES_DB: sara
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks: [ backend ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sara"]
      interval: 10s
      timeout: 5s
      retries: 5

  # lightweight canary container used by CI to prove the stack came up
  healthcheck:
    image: python:3.12-alpine
    depends_on:
      redis:   
        condition: service_healthy 
      nats:    
        condition: service_healthy
      postgres: 
        condition: service_healthy
    command: ["python", "-u", "/opt/health_check.py"]
    volumes:
      - ../scripts/health_check.py:/opt/health_check.py:ro
    networks: [ backend ]

volumes:
  redis-data:
  pg-data:

networks:
  backend:
    driver: bridge

