global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs: [{targets: ['prometheus:9090']}]

  - job_name: node
    static_configs: [{targets: ['node-exporter:9100']}]

  - job_name: traefik
    metrics_path: /metrics          # Traefik will expose this at :8080/metrics
    static_configs: [{targets: ['traefik:8080']}]

  - job_name: nats
    metrics_path: /metrics
    params: { format: ['prometheus'] }
    static_configs: [{targets: ['nats:8222']}]

  - job_name: temporal
    metrics_path: /metrics
    static_configs: [{targets: ['temporal:9090']}]

  - job_name: gateway
    metrics_path: /metrics
    static_configs: [{targets: ['gateway:8000']}]

  - job_name: dialogue_worker
    metrics_path: /metrics
    static_configs: [{targets: ['dialogue_worker:8000']}]


