"""revert_embedding_to_vector_and_fix_message_parts_final

Revision ID: 1d18f3a85c64
Revises: d9a46f623b5d
Create Date: 2025-05-24 08:07:11.318933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector # Manual import for Vector type

# revision identifiers, used by Alembic.
revision: str = '1d18f3a85c64'
down_revision: Union[str, None] = 'd9a46f623b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memory', 'embedding',
               existing_type=sa.TEXT(),
               type_=Vector(1024), # Changed to Vector
               existing_nullable=True,
               # This is crucial for Postgres: tell it how to convert TEXT to VECTOR
               postgresql_using='embedding::vector(1024)')
    op.alter_column('embedding_messages', 'embedding',
               existing_type=sa.TEXT(),
               type_=Vector(1024), # Changed to Vector
               existing_nullable=True,
               # This is crucial for Postgres: tell it how to convert TEXT to VECTOR
               postgresql_using='embedding::vector(1024)')
    op.alter_column('messages_v2', 'parts',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()), # Changed to JSONB
               existing_nullable=False,
               postgresql_using='parts::jsonb')
    op.alter_column('messages_v2', 'attachments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()), # Changed to JSONB
               existing_nullable=False,
               postgresql_using='attachments::jsonb')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages_v2', 'attachments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()), # Reverted to JSON
               existing_nullable=False,
               postgresql_using='attachments::json')
    op.alter_column('messages_v2', 'parts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()), # Reverted to JSON
               existing_nullable=False,
               postgresql_using='parts::json')
    op.alter_column('embedding_messages', 'embedding',
               existing_type=Vector(1024),
               type_=sa.TEXT(), # Reverted to TEXT
               existing_nullable=True,
               postgresql_using='embedding::text')
    op.alter_column('memory', 'embedding',
               existing_type=Vector(1024),
               type_=sa.TEXT(), # Reverted to TEXT
               existing_nullable=True,
               postgresql_using='embedding::text')
    # ### end Alembic commands ###
