name: Deploy to Infra VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Anubis
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Infra VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 10.185.1.76              # ✅ use your actual VM IP here
          username: david                # ✅ use the actual user (not "ubuntu" if it doesn’t exist)
          key: ${{ secrets.INFRA_SSH_KEY }}
          script: |
            cd /opt/sara-ai/compose
            docker compose pull
            docker compose up -d

