name: Deploy to Infra VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # 1) checkout just so we can copy code via SSH
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) SSH into the VM and run EVERYTHING there
      - name: SSH & Deploy to Infra VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 10.185.1.76
          username: david
          key: ${{ secrets.INFRA_SSH_KEY }}
          script: |
            set -euxo pipefail

            cd /opt/sara-ai

            # generate the .env on the VM
            cat > .env <<EOF
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            NEO4J_PASSWORD=${{ secrets.NEO4J_PASSWORD }}
            MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}
            MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}
            LETSENCRYPT_EMAIL=${{ secrets.LETSENCRYPT_EMAIL }}
            EOF

            # copy it where Compose will pick it up
            cp .env compose/.env

            # run Compose only on the VM
            cd compose
            docker compose -f core.yml down -v
            docker compose -f core.yml pull
            docker compose -f core.yml up -d --wait
