name: Deploy to Infra VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH & Deploy to Infra VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 10.185.1.76
          username: david
          key: ${{ secrets.INFRA_SSH_KEY }}
          script: |
            set -euo pipefail

            cd /opt/sara-ai

            # Regenerate .env
            cat > .env <<EOF
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            NEO4J_PASSWORD=${{ secrets.NEO4J_PASSWORD }}
            MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}
            MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}
            LETSENCRYPT_EMAIL=${{ secrets.LETSENCRYPT_EMAIL }}
            EOF

            # copy for Compose
            cp .env compose/.env

            cd compose

            # tear down everything
            docker compose -f core.yml down -v

            # pull new images
            docker compose -f core.yml pull

            # bring up only the primary services (no healthcheck orchestrator)
            docker compose -f core.yml up -d \
              redis \
              nats \
              postgres \
              neo4j \
              minio \
              temporal \
              traefik \
              gateway
