name: Deploy to Infra VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH & Deploy to Infra VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 10.185.1.76
          username: david
          key: ${{ secrets.INFRA_SSH_KEY }}
          script: |
            set -euo pipefail
            PROJECT=sara-core
            cd /opt/sara-ai

            # Regenerate .env
            cat > .env <<EOF
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            NEO4J_PASSWORD=${{ secrets.NEO4J_PASSWORD }}
            MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}
            MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}
            LETSENCRYPT_EMAIL=${{ secrets.LETSENCRYPT_EMAIL }}
            EOF

            docker compose \
               --env-file ../.env \             # points at the file you just wrote
               -p "$PROJECT" \                  # idempotent container names
               -f core.yml \
               down --volumes --remove-orphans  # 1️⃣ cleanly stop previous run
 
             docker compose \
               --env-file ../.env \
               -p "$PROJECT" \
               -f core.yml \
               -f monitoring.yml \
               pull --quiet                     # 2️⃣ fetch newer images
 
             docker compose \
               --env-file ../.env \
               -p "$PROJECT" \
               -f core.yml \
               -f monitoring.yml \
               up -d --force-recreate           # 3️⃣ start (or replace) services
 
             docker compose \
               --env-file ../.env \
               -p "$PROJECT" \
               -f core.yml \
               ps                                # 4️⃣ show final state for logs

